### ISSUE TITLE
Official plugin?

### ISSUE THREAD

**Issue by plainspace** [destefanis/auto-theme#3]
Is this plugin going to be installable from Figma?

**Comment by destefanis** [comment]
Hi @plainspace! It won't, simply because it's not built to walk you through setting up a theme and is hard coded right now to work with Discord. However, I did document it so other teams could hard code their own values for each theme and use as they liked!

Official plugins require using jsonbin.io or other login services to sync which I didn't want to deal with since our team can just use this!

Hope that makes sense!
